version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase  # Optional: specify a default database
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  app:
    build: 
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    restart: always
    ports:
      - 3000:3001  # Map the container's port 3000 to the host's port 3000
    depends_on:
      - db  # Ensure that the db service is started before the app
    environment:
      DATABASE_URL: ${DATABASE_URL} 

# username: root
# pass: example
