version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:example@db:5432/mydatabase
      NODE_OPTIONS: "--max-old-space-size=4096"  # Increase memory limit
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:3001/health || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
